services:
  postgres:
    image: postgres:15-alpine
    container_name: fomu_nexus_db
    environment:
      POSTGRES_USER: nexus_admin
      POSTGRES_PASSWORD: nexus_password_2026
      POSTGRES_DB: fomu_nexus
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
